config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  resources :users, only: [:new, :create, :show]
  resources :ideas
  resources :categories
  resources :images


  get "/signup",    to: 'users#new'
  delete "/logout", to: 'sessions#destroy'
  get "/login",     to: 'sessions#new'
  post "/login",    to: 'sessions#create'

  namespace :admin do
    resources :categories, only: ['index']
    resources :images
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ideas, dependent: :destroy
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :idea_images
  has_many :images, through: :idea_images, dependent: :destroy
  belongs_to :category

end

app/models/idea_image.rb
class IdeaImage < ActiveRecord::Base
  belongs_to :idea
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :idea_images
  has_many :ideas, through: :idea_images
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ideas
  has_secure_password

  validates :name, :email, presence: true,
                         uniqueness: true

  enum role: [:default, :admin]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/signup' unless current_user
  end

  def require_auth
    redirect_to login unless current_user
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  before_action :require_auth

  def index
    @ideas = Idea.all
  end

  def show
    @images = Image.all
  end

  def new
    @categories = Category.all
    @idea = Idea.new
  end

  def edit
    @categories = Category.all
    @images = Image.all
  end

  def create
    @idea = @current_user.ideas.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_idea
      @idea = Idea.find(params[:id])
    end

    def idea_params
      params.require(:idea).permit(:content, :category_id)
    end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:index]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  def new
    @image = Image.new
  end

  def edit
  end

  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:path)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id

      redirect_to user_path(user)
    else
      redirect_to login_path
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      @current_user = user

      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br><br>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="btn waves-effect waves-light">
    <i class="material-icons right"><%= form.submit %></i>
  </div>
  
<% end %>

app/views/categories/_header.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "Your Profile", user_path(@current_user) %></li>
  <li><%= link_to "Logout", logout_path, method: :delete %></li>
</ul>
<nav>
  <div class="nav-wrapper blue">
    <a href="#" class="brand-logo"><h3>IdeaBox</h3></a>
    <a href="#!" class="brand-logo center small">Categories</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to 'Ideas', ideas_path %></li>
      <li class="active"><%= link_to 'Categories', categories_path %></li>
      <li><%= link_to 'Images', images_path %></li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row center-align">
<%= button_to "New Category", new_category_path, class: "waves-effect waves-light btn-small", method: :get  if current_user && current_user.admin? do %>
<a class="waves-effect waves-light btn blue center-align">New Category</a>
<% end %>
</div>
    <div class="col s6 m3">
     <% @categories.each do |category| %>
      <div class="card">
        <div class="card-content ">
          <span class="card-title center"><%= category.name %></span>
        </div>
        <% if current_user && current_user.admin? %>
        <div class="card-action white center">
          <td><%= link_to category, class: "waves-effect waves-light btn-small" do %>
            <i class="material-icons">info</i>
          <% end %></td>
          <td><%= link_to edit_category_path(category), class: "waves-effect waves-light btn-small" do %>
            <i class="material-icons">edit</i>
          <% end %></td>
          <td><%= link_to category, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn-small" do %>
            <i class="material-icons">delete</i>
          <% end %></td>
      <% end %>
      </div>

    </div>
        <% end %>
  </div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<% @category.ideas.each do |idea| %>
<p> <%= idea.content %> </p>
<% end %>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/ideas/_form.html.erb
<div class="row">
  <%= form_with(model: idea, local: true) do |form| %>
    <% if idea.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

        <ul>
        <% idea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <div class="col s9">
    <div class="field">
      <%= form.label :content %>
      <%= form.text_field :content, id: :idea_content %>
    </div>
  </div>
</div>
  <div class="row">
  <div class="col s4">
     <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category" }, class: "browser-default" %>

  </div class="col s2">
    <div class="btn waves-effect waves-light">
  <i class="material-icons right"><%= form.submit %></i>
    </div>

</button>
  </div>
</div>
  <% end %>
</div>

app/views/ideas/_header.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "Your Profile", user_path(@current_user) %></li>
  <li><%= link_to "Logout", logout_path, method: :delete %></li>
</ul>
<nav>
  <div class="nav-wrapper blue">
    <a href="#" class="brand-logo"><h3>IdeaBox</h3></a>
    <a href="#!" class="brand-logo center small">Ideas</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li class="active"><%= link_to 'Ideas', ideas_path %></li>
      <li><%= link_to 'Categories', categories_path %></li>
      <li><%= link_to 'Images', images_path %></li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<%= link_to 'New Idea', new_idea_path %>
<br>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<% if current_user && current_user.admin?%>
  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.content %></td>
        <td><%= idea.category.name %></td>
        <td><%= link_to idea, class: "waves-effect waves-light btn-small" do %>
          <i class="material-icons">info</i>
        <% end %></td>
        <td><%= link_to edit_idea_path(idea), class: "waves-effect waves-light btn-small" do %>
          <i class="material-icons">edit</i>
        <% end %></td>
        <td><%= link_to idea, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn-small" do %>
          <i class="material-icons">delete</i>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
  <% else %>
  <tbody>
    <% @current_user.ideas.each do |idea| %>
      <tr>
        <td><%= idea.content %></td>
        <td><%= idea.category.name %></td>

        <td><%= link_to edit_idea_path(idea), class: "waves-effect waves-light btn-small" do %>
          <i class="material-icons">edit</i>
        <% end %></td>
        <td><%= link_to idea, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn-small" do %>
          <i class="material-icons">delete</i>
        <% end %></td>
      </tr>
    <% end %>
        <% end %>
  </tbody>
</table>

app/views/ideas/new.html.erb
<div class="center"><h1>New Idea</h1></div>
<br>
<div class="container center">
<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>
</div>

app/views/ideas/new_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.content %></td>
        <td><%= idea.category.name %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @idea.content %>
</p>

<p>
  <strong>Category:</strong>
  <%= @idea.category.name %>
</p>

<p>
  <strong>Images:</strong>
    <br>
    <% @idea.images.each do |image| %>
      <img src="<%= image.path %>">
    <% end %>
</p>

<%= form.collection_select :image_id, @images.all, :id, :path, { prompt: "Choose an Image" }, class: "browser-default" %>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :image_name %>
  </div>

  <div class="field">
    <%= form.label :path %>
    <%= form.text_field :path, id: :image_path %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/_header.html.erb
<ul id="dropdown1" class="dropdown-content">
</ul>
<nav>
  <div class="nav-wrapper blue">
    <a href="#" class="brand-logo"><h3>IdeaBox</h3></a>
    <a href="#!" class="brand-logo center small">Images</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to 'Ideas', ideas_path %></li>
      <li><%= link_to 'Categories', categories_path %></li>
      <li class="active"><%= link_to 'Images', images_path %></li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row center-align">
<%= link_to new_image_path, class: "waves-effect waves-light btn-small"  if current_user && current_user.admin? do %>
<a class="waves-effect waves-light btn blue center-align">New image</a>
<% end %>
</div>
<br>
<div class="col s6 m3">
 <% @images.each do |image| %>
  <div class="card">
    <div class="card-content ">
      <span class="card-title center"><%= image.name %></span>
    </div>
    <% if current_user && current_user.admin? %>
    <div class="card-action white center">
      <td><%= link_to image, class: "waves-effect waves-light btn-small" do %>
        <i class="material-icons">info</i>
      <% end %></td>
      <td><%= link_to edit_image_path(image), class: "waves-effect waves-light btn-small" do %>
        <i class="material-icons">edit</i>
      <% end %></td>
      <td><%= link_to image, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn-small" do %>
        <i class="material-icons">delete</i>
      <% end %></td>
  <% end %>
  </div>

</div>
    <% end %>
</div>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @image.name %>
</p>
<img src="<%= @image.path %>">
<p>
  <strong>Path:</strong>
  <%= @image.path %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'header'%>
    <%= yield %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_header.html.erb
<nav>
  <div class="nav-wrapper blue">
    <a href="#" class="brand-logo"><h3>IdeaBox</h3></a>
    <a href="#!" class="brand-logo center small">Categories</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to 'Ideas', ideas_path %></li>
      <li><%= link_to 'Categories', categories_path %></li>
      <li><%= link_to 'Images', images_path %></li>
    </ul>
  </div>
</nav>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<h2>Your Ideas:</h2>
<% @user.ideas.each do |idea| %>
<div class="row">
<div class="col s4">
  <div class="card medium hoverable">
    <div class="card-image">
      <div class="responsive-img">
      <img src="<%= Faker::LoremPixel.image %>">
    </div>
  </div>
    <div class="card-stacked">
      <div class="card-content">
        <p><%= idea.content %></p>
      </div>
      <div class="card-action">
        <a><%= link_to 'Edit', edit_idea_path(idea) %></a>
      </div>
    </div>
  </div>

</div>
<% end %>
</div>

<%= link_to 'Back', users_path %>

app/views/welcome/_header.html.erb
<nav>
  <div class="nav-wrapper blue">
    <a href="#" class="brand-logo center">IdeaBox</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to 'Ideas', root_path %></li>
      <li><%= link_to 'Categories', root_path %></li>
      <li><%= link_to 'Images', root_path %></li>
    </ul>
  </div>
</nav>

app/views/welcome/index.html.erb
<br>
<div class="row center-align">
  <h3>Welcome to the Idea Box</h3>
  <br>
  <p>Please use the links below to create a new user or login.</p>
  <p>The administrator account details are "admin@admin.com" password "adminpass".</p>
  <p>A populated user account can be accessed with "OllieWilliams@fox.com" and password "ollie".</p>
<%= link_to 'Login', login_path %>
<br>
<%= link_to 'Signup', signup_path %>
</div>